package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Administrateur generated by hbm2java
 */
@Entity
@Table(name="administrateur"
    ,schema="public"
)
public class Administrateur  implements java.io.Serializable {


     private String codepersonne;
     private Personne personne;
     private Integer supercode;
     private Set boutiques = new HashSet(0);

    public Administrateur() {
    }

	
    public Administrateur(Personne personne) {
        this.personne = personne;
    }
    public Administrateur(Personne personne, Integer supercode, Set boutiques) {
       this.personne = personne;
       this.supercode = supercode;
       this.boutiques = boutiques;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="personne"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="codepersonne", nullable=false, length=40)
    public String getCodepersonne() {
        return this.codepersonne;
    }
    
    public void setCodepersonne(String codepersonne) {
        this.codepersonne = codepersonne;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Personne getPersonne() {
        return this.personne;
    }
    
    public void setPersonne(Personne personne) {
        this.personne = personne;
    }

    
    @Column(name="supercode")
    public Integer getSupercode() {
        return this.supercode;
    }
    
    public void setSupercode(Integer supercode) {
        this.supercode = supercode;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="administrateur")
    public Set getBoutiques() {
        return this.boutiques;
    }
    
    public void setBoutiques(Set boutiques) {
        this.boutiques = boutiques;
    }




}


