package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Boutique generated by hbm2java
 */
@Entity
@Table(name="boutique"
    ,schema="public"
)
public class Boutique  implements java.io.Serializable {


     private String codeboutique;
     private Administrateur administrateur;
     private String telephone;
     private String nom;
     private String email;
     private String adresse;
     private String ville;
     private String pays;
     private String datecreation;
     private Set employes = new HashSet(0);

    public Boutique() {
    }

	
    public Boutique(String codeboutique, Administrateur administrateur, String datecreation) {
        this.codeboutique = codeboutique;
        this.administrateur = administrateur;
        this.datecreation = datecreation;
    }
    public Boutique(String codeboutique, Administrateur administrateur, String telephone, String nom, String email, String adresse, String ville, String pays, String datecreation, Set employes) {
       this.codeboutique = codeboutique;
       this.administrateur = administrateur;
       this.telephone = telephone;
       this.nom = nom;
       this.email = email;
       this.adresse = adresse;
       this.ville = ville;
       this.pays = pays;
       this.datecreation = datecreation;
       this.employes = employes;
    }
   
     @Id 

    
    @Column(name="codeboutique", nullable=false, length=40)
    public String getCodeboutique() {
        return this.codeboutique;
    }
    
    public void setCodeboutique(String codeboutique) {
        this.codeboutique = codeboutique;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codeadmin", nullable=false)
    public Administrateur getAdministrateur() {
        return this.administrateur;
    }
    
    public void setAdministrateur(Administrateur administrateur) {
        this.administrateur = administrateur;
    }

    
    @Column(name="telephone", length=50)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    
    @Column(name="nom", length=50)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="adresse", length=50)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="ville", length=50)
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }

    
    @Column(name="pays", length=50)
    public String getPays() {
        return this.pays;
    }
    
    public void setPays(String pays) {
        this.pays = pays;
    }

    
    @Column(name="datecreation", nullable=false, length=40)
    public String getDatecreation() {
        return this.datecreation;
    }
    
    public void setDatecreation(String datecreation) {
        this.datecreation = datecreation;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="boutique")
    public Set getEmployes() {
        return this.employes;
    }
    
    public void setEmployes(Set employes) {
        this.employes = employes;
    }




}


