package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CalendrierserviceId generated by hbm2java
 */
@Embeddable
public class CalendrierserviceId  implements java.io.Serializable {


     private String codepersonne;
     private int codejour;
     private Date datepriseservice;
     private Date heuredebut;
     private Date heurefin;

    public CalendrierserviceId() {
    }

    public CalendrierserviceId(String codepersonne, int codejour, Date datepriseservice, Date heuredebut, Date heurefin) {
       this.codepersonne = codepersonne;
       this.codejour = codejour;
       this.datepriseservice = datepriseservice;
       this.heuredebut = heuredebut;
       this.heurefin = heurefin;
    }
   


    @Column(name="codepersonne", nullable=false, length=40)
    public String getCodepersonne() {
        return this.codepersonne;
    }
    
    public void setCodepersonne(String codepersonne) {
        this.codepersonne = codepersonne;
    }


    @Column(name="codejour", nullable=false)
    public int getCodejour() {
        return this.codejour;
    }
    
    public void setCodejour(int codejour) {
        this.codejour = codejour;
    }


    @Column(name="datepriseservice", nullable=false, length=13)
    public Date getDatepriseservice() {
        return this.datepriseservice;
    }
    
    public void setDatepriseservice(Date datepriseservice) {
        this.datepriseservice = datepriseservice;
    }


    @Column(name="heuredebut", nullable=false, length=15)
    public Date getHeuredebut() {
        return this.heuredebut;
    }
    
    public void setHeuredebut(Date heuredebut) {
        this.heuredebut = heuredebut;
    }


    @Column(name="heurefin", nullable=false, length=15)
    public Date getHeurefin() {
        return this.heurefin;
    }
    
    public void setHeurefin(Date heurefin) {
        this.heurefin = heurefin;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CalendrierserviceId) ) return false;
		 CalendrierserviceId castOther = ( CalendrierserviceId ) other; 
         
		 return ( (this.getCodepersonne()==castOther.getCodepersonne()) || ( this.getCodepersonne()!=null && castOther.getCodepersonne()!=null && this.getCodepersonne().equals(castOther.getCodepersonne()) ) )
 && (this.getCodejour()==castOther.getCodejour())
 && ( (this.getDatepriseservice()==castOther.getDatepriseservice()) || ( this.getDatepriseservice()!=null && castOther.getDatepriseservice()!=null && this.getDatepriseservice().equals(castOther.getDatepriseservice()) ) )
 && ( (this.getHeuredebut()==castOther.getHeuredebut()) || ( this.getHeuredebut()!=null && castOther.getHeuredebut()!=null && this.getHeuredebut().equals(castOther.getHeuredebut()) ) )
 && ( (this.getHeurefin()==castOther.getHeurefin()) || ( this.getHeurefin()!=null && castOther.getHeurefin()!=null && this.getHeurefin().equals(castOther.getHeurefin()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodepersonne() == null ? 0 : this.getCodepersonne().hashCode() );
         result = 37 * result + this.getCodejour();
         result = 37 * result + ( getDatepriseservice() == null ? 0 : this.getDatepriseservice().hashCode() );
         result = 37 * result + ( getHeuredebut() == null ? 0 : this.getHeuredebut().hashCode() );
         result = 37 * result + ( getHeurefin() == null ? 0 : this.getHeurefin().hashCode() );
         return result;
   }   


}


