package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Calendrierservice generated by hbm2java
 */
@Entity
@Table(name="calendrierservice"
    ,schema="public"
)
public class Calendrierservice  implements java.io.Serializable {


     private CalendrierserviceId id;
     private Employe employe;
     private Jour jour;

    public Calendrierservice() {
    }

    public Calendrierservice(CalendrierserviceId id, Employe employe, Jour jour) {
       this.id = id;
       this.employe = employe;
       this.jour = jour;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codepersonne", column=@Column(name="codepersonne", nullable=false, length=40) ), 
        @AttributeOverride(name="codejour", column=@Column(name="codejour", nullable=false) ), 
        @AttributeOverride(name="datepriseservice", column=@Column(name="datepriseservice", nullable=false, length=13) ), 
        @AttributeOverride(name="heuredebut", column=@Column(name="heuredebut", nullable=false, length=15) ), 
        @AttributeOverride(name="heurefin", column=@Column(name="heurefin", nullable=false, length=15) ) } )
    public CalendrierserviceId getId() {
        return this.id;
    }
    
    public void setId(CalendrierserviceId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codepersonne", nullable=false, insertable=false, updatable=false)
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codejour", nullable=false, insertable=false, updatable=false)
    public Jour getJour() {
        return this.jour;
    }
    
    public void setJour(Jour jour) {
        this.jour = jour;
    }




}


