package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="client"
    ,schema="public"
)
public class Client  implements java.io.Serializable {


     private String codepersonne;
     private Personne personne;
     private String adresselivraison;
     private String categorie;
     private Integer label;
     private Boolean vip;
     private Set groupes = new HashSet(0);
     private Set panierclients = new HashSet(0);

    public Client() {
    }

	
    public Client(Personne personne) {
        this.personne = personne;
    }
    public Client(Personne personne, String adresselivraison, String categorie, Integer label, Boolean vip, Set groupes, Set panierclients) {
       this.personne = personne;
       this.adresselivraison = adresselivraison;
       this.categorie = categorie;
       this.label = label;
       this.vip = vip;
       this.groupes = groupes;
       this.panierclients = panierclients;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="personne"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="codepersonne", nullable=false, length=40)
    public String getCodepersonne() {
        return this.codepersonne;
    }
    
    public void setCodepersonne(String codepersonne) {
        this.codepersonne = codepersonne;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Personne getPersonne() {
        return this.personne;
    }
    
    public void setPersonne(Personne personne) {
        this.personne = personne;
    }

    
    @Column(name="adresselivraison", length=254)
    public String getAdresselivraison() {
        return this.adresselivraison;
    }
    
    public void setAdresselivraison(String adresselivraison) {
        this.adresselivraison = adresselivraison;
    }

    
    @Column(name="categorie", length=50)
    public String getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(String categorie) {
        this.categorie = categorie;
    }

    
    @Column(name="label")
    public Integer getLabel() {
        return this.label;
    }
    
    public void setLabel(Integer label) {
        this.label = label;
    }

    
    @Column(name="vip")
    public Boolean getVip() {
        return this.vip;
    }
    
    public void setVip(Boolean vip) {
        this.vip = vip;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="detailsgroupe", schema="public", joinColumns = { 
        @JoinColumn(name="codepersonne", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="codegroupe", nullable=false, updatable=false) })
    public Set getGroupes() {
        return this.groupes;
    }
    
    public void setGroupes(Set groupes) {
        this.groupes = groupes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set getPanierclients() {
        return this.panierclients;
    }
    
    public void setPanierclients(Set panierclients) {
        this.panierclients = panierclients;
    }




}


