package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name="commande"
    ,schema="public"
)
public class Commande  implements java.io.Serializable {


     private String codecommande;
     private Fournisseur fournisseur;
     private Gerant gerant;
     private Stock stock;
     private String type;
     private Date datecommande;
     private String facture;
     private Integer etat;
     private String libelle;
     private Set devises = new HashSet(0);
     private Set lignecommandes = new HashSet(0);

    public Commande() {
    }

	
    public Commande(String codecommande, Fournisseur fournisseur, Gerant gerant) {
        this.codecommande = codecommande;
        this.fournisseur = fournisseur;
        this.gerant = gerant;
    }
    public Commande(String codecommande, Fournisseur fournisseur, Gerant gerant, Stock stock, String type, Date datecommande, String facture, Integer etat, String libelle, Set devises, Set lignecommandes) {
       this.codecommande = codecommande;
       this.fournisseur = fournisseur;
       this.gerant = gerant;
       this.stock = stock;
       this.type = type;
       this.datecommande = datecommande;
       this.facture = facture;
       this.etat = etat;
       this.libelle = libelle;
       this.devises = devises;
       this.lignecommandes = lignecommandes;
    }
   
     @Id 

    
    @Column(name="codecommande", nullable=false, length=50)
    public String getCodecommande() {
        return this.codecommande;
    }
    
    public void setCodecommande(String codecommande) {
        this.codecommande = codecommande;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codefournisseur", nullable=false)
    public Fournisseur getFournisseur() {
        return this.fournisseur;
    }
    
    public void setFournisseur(Fournisseur fournisseur) {
        this.fournisseur = fournisseur;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codegerant", nullable=false)
    public Gerant getGerant() {
        return this.gerant;
    }
    
    public void setGerant(Gerant gerant) {
        this.gerant = gerant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codestock")
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }

    
    @Column(name="type", length=50)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datecommande", length=13)
    public Date getDatecommande() {
        return this.datecommande;
    }
    
    public void setDatecommande(Date datecommande) {
        this.datecommande = datecommande;
    }

    
    @Column(name="facture", length=254)
    public String getFacture() {
        return this.facture;
    }
    
    public void setFacture(String facture) {
        this.facture = facture;
    }

    
    @Column(name="etat")
    public Integer getEtat() {
        return this.etat;
    }
    
    public void setEtat(Integer etat) {
        this.etat = etat;
    }

    
    @Column(name="libelle", length=50)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="commande")
    public Set getDevises() {
        return this.devises;
    }
    
    public void setDevises(Set devises) {
        this.devises = devises;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="commande")
    public Set getLignecommandes() {
        return this.lignecommandes;
    }
    
    public void setLignecommandes(Set lignecommandes) {
        this.lignecommandes = lignecommandes;
    }




}


