package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Couloir generated by hbm2java
 */
@Entity
@Table(name="couloir"
    ,schema="public"
)
public class Couloir  implements java.io.Serializable {


     private int codecouloir;
     private String libelle;
     private Set etageres = new HashSet(0);

    public Couloir() {
    }

	
    public Couloir(int codecouloir) {
        this.codecouloir = codecouloir;
    }
    public Couloir(int codecouloir, String libelle, Set etageres) {
       this.codecouloir = codecouloir;
       this.libelle = libelle;
       this.etageres = etageres;
    }
   
     @Id 

    
    @Column(name="codecouloir", nullable=false)
    public int getCodecouloir() {
        return this.codecouloir;
    }
    
    public void setCodecouloir(int codecouloir) {
        this.codecouloir = codecouloir;
    }

    
    @Column(name="libelle", length=45)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="couloir")
    public Set getEtageres() {
        return this.etageres;
    }
    
    public void setEtageres(Set etageres) {
        this.etageres = etageres;
    }




}


