package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Devis generated by hbm2java
 */
@Entity
@Table(name="devis"
    ,schema="public"
)
public class Devis  implements java.io.Serializable {


     private String codedevis;
     private Commande commande;
     private Fournisseur fournisseur;
     private String libelle;
     private Integer etat;
     private Date datedevis;
     private Set lignedevises = new HashSet(0);

    public Devis() {
    }

	
    public Devis(String codedevis, Commande commande, Fournisseur fournisseur) {
        this.codedevis = codedevis;
        this.commande = commande;
        this.fournisseur = fournisseur;
    }
    public Devis(String codedevis, Commande commande, Fournisseur fournisseur, String libelle, Integer etat, Date datedevis, Set lignedevises) {
       this.codedevis = codedevis;
       this.commande = commande;
       this.fournisseur = fournisseur;
       this.libelle = libelle;
       this.etat = etat;
       this.datedevis = datedevis;
       this.lignedevises = lignedevises;
    }
   
     @Id 

    
    @Column(name="codedevis", nullable=false, length=50)
    public String getCodedevis() {
        return this.codedevis;
    }
    
    public void setCodedevis(String codedevis) {
        this.codedevis = codedevis;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codecommande", nullable=false)
    public Commande getCommande() {
        return this.commande;
    }
    
    public void setCommande(Commande commande) {
        this.commande = commande;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codefournisseur", nullable=false)
    public Fournisseur getFournisseur() {
        return this.fournisseur;
    }
    
    public void setFournisseur(Fournisseur fournisseur) {
        this.fournisseur = fournisseur;
    }

    
    @Column(name="libelle", length=50)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="etat")
    public Integer getEtat() {
        return this.etat;
    }
    
    public void setEtat(Integer etat) {
        this.etat = etat;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datedevis", length=13)
    public Date getDatedevis() {
        return this.datedevis;
    }
    
    public void setDatedevis(Date datedevis) {
        this.datedevis = datedevis;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="devis")
    public Set getLignedevises() {
        return this.lignedevises;
    }
    
    public void setLignedevises(Set lignedevises) {
        this.lignedevises = lignedevises;
    }




}


