package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Employe generated by hbm2java
 */
@Entity
@Table(name="employe"
    ,schema="public"
)
public class Employe  implements java.io.Serializable {


     private String codepersonne;
     private Boutique boutique;
     private Personne personne;
     private String fonction;
     private Set calendrierservices = new HashSet(0);
     private Livreur livreur;
     private Gerant gerant;
     private Caissier caissier;

    public Employe() {
    }

	
    public Employe(Boutique boutique, Personne personne, String fonction) {
        this.boutique = boutique;
        this.personne = personne;
        this.fonction = fonction;
    }
    public Employe(Boutique boutique, Personne personne, String fonction, Set calendrierservices, Livreur livreur, Gerant gerant, Caissier caissier) {
       this.boutique = boutique;
       this.personne = personne;
       this.fonction = fonction;
       this.calendrierservices = calendrierservices;
       this.livreur = livreur;
       this.gerant = gerant;
       this.caissier = caissier;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="personne"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="codepersonne", nullable=false, length=40)
    public String getCodepersonne() {
        return this.codepersonne;
    }
    
    public void setCodepersonne(String codepersonne) {
        this.codepersonne = codepersonne;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codeboutique", nullable=false)
    public Boutique getBoutique() {
        return this.boutique;
    }
    
    public void setBoutique(Boutique boutique) {
        this.boutique = boutique;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Personne getPersonne() {
        return this.personne;
    }
    
    public void setPersonne(Personne personne) {
        this.personne = personne;
    }

    
    @Column(name="fonction", nullable=false, length=20)
    public String getFonction() {
        return this.fonction;
    }
    
    public void setFonction(String fonction) {
        this.fonction = fonction;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employe")
    public Set getCalendrierservices() {
        return this.calendrierservices;
    }
    
    public void setCalendrierservices(Set calendrierservices) {
        this.calendrierservices = calendrierservices;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="employe")
    public Livreur getLivreur() {
        return this.livreur;
    }
    
    public void setLivreur(Livreur livreur) {
        this.livreur = livreur;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="employe")
    public Gerant getGerant() {
        return this.gerant;
    }
    
    public void setGerant(Gerant gerant) {
        this.gerant = gerant;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="employe")
    public Caissier getCaissier() {
        return this.caissier;
    }
    
    public void setCaissier(Caissier caissier) {
        this.caissier = caissier;
    }




}


