package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Etagere generated by hbm2java
 */
@Entity
@Table(name="etagere"
    ,schema="public"
)
public class Etagere  implements java.io.Serializable {


     private int codeetagere;
     private Couloir couloir;
     private String nom;
     private String libelle;
     private Integer capacite;
     private Integer occupation;
     private Boolean plein;
     private Set produits = new HashSet(0);

    public Etagere() {
    }

	
    public Etagere(int codeetagere) {
        this.codeetagere = codeetagere;
    }
    public Etagere(int codeetagere, Couloir couloir, String nom, String libelle, Integer capacite, Integer occupation, Boolean plein, Set produits) {
       this.codeetagere = codeetagere;
       this.couloir = couloir;
       this.nom = nom;
       this.libelle = libelle;
       this.capacite = capacite;
       this.occupation = occupation;
       this.plein = plein;
       this.produits = produits;
    }
   
     @Id 

    
    @Column(name="codeetagere", nullable=false)
    public int getCodeetagere() {
        return this.codeetagere;
    }
    
    public void setCodeetagere(int codeetagere) {
        this.codeetagere = codeetagere;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codecouloir")
    public Couloir getCouloir() {
        return this.couloir;
    }
    
    public void setCouloir(Couloir couloir) {
        this.couloir = couloir;
    }

    
    @Column(name="nom", length=20)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="libelle", length=40)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="capacite")
    public Integer getCapacite() {
        return this.capacite;
    }
    
    public void setCapacite(Integer capacite) {
        this.capacite = capacite;
    }

    
    @Column(name="occupation")
    public Integer getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(Integer occupation) {
        this.occupation = occupation;
    }

    
    @Column(name="plein")
    public Boolean getPlein() {
        return this.plein;
    }
    
    public void setPlein(Boolean plein) {
        this.plein = plein;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="etagere")
    public Set getProduits() {
        return this.produits;
    }
    
    public void setProduits(Set produits) {
        this.produits = produits;
    }




}


