package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Famille generated by hbm2java
 */
@Entity
@Table(name="famille"
    ,schema="public"
)
public class Famille  implements java.io.Serializable {


     private String codefamille;
     private String nom;
     private String libelle;
     private Boolean sucre;
     private Boolean alcoolise;
     private Boolean gazeuse;
     private BigDecimal degresalcool;
     private Boolean naturel;
     private Boolean mineral;
     private String saveur;
     private String format;
     private Integer quantite;
     private Set lignecommandes = new HashSet(0);
     private Set produits = new HashSet(0);
     private Set lignedevises = new HashSet(0);
     private Set ressourcemedias = new HashSet(0);

    public Famille() {
    }

	
    public Famille(String codefamille) {
        this.codefamille = codefamille;
    }
    public Famille(String codefamille, String nom, String libelle, Boolean sucre, Boolean alcoolise, Boolean gazeuse, BigDecimal degresalcool, Boolean naturel, Boolean mineral, String saveur, String format, Integer quantite, Set lignecommandes, Set produits, Set lignedevises, Set ressourcemedias) {
       this.codefamille = codefamille;
       this.nom = nom;
       this.libelle = libelle;
       this.sucre = sucre;
       this.alcoolise = alcoolise;
       this.gazeuse = gazeuse;
       this.degresalcool = degresalcool;
       this.naturel = naturel;
       this.mineral = mineral;
       this.saveur = saveur;
       this.format = format;
       this.quantite = quantite;
       this.lignecommandes = lignecommandes;
       this.produits = produits;
       this.lignedevises = lignedevises;
       this.ressourcemedias = ressourcemedias;
    }
   
     @Id 

    
    @Column(name="codefamille", nullable=false, length=254)
    public String getCodefamille() {
        return this.codefamille;
    }
    
    public void setCodefamille(String codefamille) {
        this.codefamille = codefamille;
    }

    
    @Column(name="nom", length=254)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="libelle", length=254)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="sucre")
    public Boolean getSucre() {
        return this.sucre;
    }
    
    public void setSucre(Boolean sucre) {
        this.sucre = sucre;
    }

    
    @Column(name="alcoolise")
    public Boolean getAlcoolise() {
        return this.alcoolise;
    }
    
    public void setAlcoolise(Boolean alcoolise) {
        this.alcoolise = alcoolise;
    }

    
    @Column(name="gazeuse")
    public Boolean getGazeuse() {
        return this.gazeuse;
    }
    
    public void setGazeuse(Boolean gazeuse) {
        this.gazeuse = gazeuse;
    }

    
    @Column(name="degresalcool", precision=131089, scale=0)
    public BigDecimal getDegresalcool() {
        return this.degresalcool;
    }
    
    public void setDegresalcool(BigDecimal degresalcool) {
        this.degresalcool = degresalcool;
    }

    
    @Column(name="naturel")
    public Boolean getNaturel() {
        return this.naturel;
    }
    
    public void setNaturel(Boolean naturel) {
        this.naturel = naturel;
    }

    
    @Column(name="mineral")
    public Boolean getMineral() {
        return this.mineral;
    }
    
    public void setMineral(Boolean mineral) {
        this.mineral = mineral;
    }

    
    @Column(name="saveur", length=50)
    public String getSaveur() {
        return this.saveur;
    }
    
    public void setSaveur(String saveur) {
        this.saveur = saveur;
    }

    
    @Column(name="format", length=50)
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }

    
    @Column(name="quantite")
    public Integer getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(Integer quantite) {
        this.quantite = quantite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="famille")
    public Set getLignecommandes() {
        return this.lignecommandes;
    }
    
    public void setLignecommandes(Set lignecommandes) {
        this.lignecommandes = lignecommandes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="famille")
    public Set getProduits() {
        return this.produits;
    }
    
    public void setProduits(Set produits) {
        this.produits = produits;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="famille")
    public Set getLignedevises() {
        return this.lignedevises;
    }
    
    public void setLignedevises(Set lignedevises) {
        this.lignedevises = lignedevises;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="famille")
    public Set getRessourcemedias() {
        return this.ressourcemedias;
    }
    
    public void setRessourcemedias(Set ressourcemedias) {
        this.ressourcemedias = ressourcemedias;
    }




}


