package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GerantprivilegeId generated by hbm2java
 */
@Embeddable
public class GerantprivilegeId  implements java.io.Serializable {


     private String codepersonne;
     private int codeprivilege;

    public GerantprivilegeId() {
    }

    public GerantprivilegeId(String codepersonne, int codeprivilege) {
       this.codepersonne = codepersonne;
       this.codeprivilege = codeprivilege;
    }
   


    @Column(name="codepersonne", nullable=false, length=40)
    public String getCodepersonne() {
        return this.codepersonne;
    }
    
    public void setCodepersonne(String codepersonne) {
        this.codepersonne = codepersonne;
    }


    @Column(name="codeprivilege", nullable=false)
    public int getCodeprivilege() {
        return this.codeprivilege;
    }
    
    public void setCodeprivilege(int codeprivilege) {
        this.codeprivilege = codeprivilege;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GerantprivilegeId) ) return false;
		 GerantprivilegeId castOther = ( GerantprivilegeId ) other; 
         
		 return ( (this.getCodepersonne()==castOther.getCodepersonne()) || ( this.getCodepersonne()!=null && castOther.getCodepersonne()!=null && this.getCodepersonne().equals(castOther.getCodepersonne()) ) )
 && (this.getCodeprivilege()==castOther.getCodeprivilege());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodepersonne() == null ? 0 : this.getCodepersonne().hashCode() );
         result = 37 * result + this.getCodeprivilege();
         return result;
   }   


}


