package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Gerantprivilege generated by hbm2java
 */
@Entity
@Table(name="gerantprivilege"
    ,schema="public"
)
public class Gerantprivilege  implements java.io.Serializable {


     private GerantprivilegeId id;
     private Gerant gerant;
     private Privilege privilege;
     private Date datedebut;
     private Date datefin;
     private Boolean illimite;
     private Boolean etat;

    public Gerantprivilege() {
    }

	
    public Gerantprivilege(GerantprivilegeId id, Gerant gerant, Privilege privilege) {
        this.id = id;
        this.gerant = gerant;
        this.privilege = privilege;
    }
    public Gerantprivilege(GerantprivilegeId id, Gerant gerant, Privilege privilege, Date datedebut, Date datefin, Boolean illimite, Boolean etat) {
       this.id = id;
       this.gerant = gerant;
       this.privilege = privilege;
       this.datedebut = datedebut;
       this.datefin = datefin;
       this.illimite = illimite;
       this.etat = etat;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codepersonne", column=@Column(name="codepersonne", nullable=false, length=40) ), 
        @AttributeOverride(name="codeprivilege", column=@Column(name="codeprivilege", nullable=false) ) } )
    public GerantprivilegeId getId() {
        return this.id;
    }
    
    public void setId(GerantprivilegeId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codepersonne", nullable=false, insertable=false, updatable=false)
    public Gerant getGerant() {
        return this.gerant;
    }
    
    public void setGerant(Gerant gerant) {
        this.gerant = gerant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codeprivilege", nullable=false, insertable=false, updatable=false)
    public Privilege getPrivilege() {
        return this.privilege;
    }
    
    public void setPrivilege(Privilege privilege) {
        this.privilege = privilege;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datedebut", length=29)
    public Date getDatedebut() {
        return this.datedebut;
    }
    
    public void setDatedebut(Date datedebut) {
        this.datedebut = datedebut;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datefin", length=29)
    public Date getDatefin() {
        return this.datefin;
    }
    
    public void setDatefin(Date datefin) {
        this.datefin = datefin;
    }

    
    @Column(name="illimite")
    public Boolean getIllimite() {
        return this.illimite;
    }
    
    public void setIllimite(Boolean illimite) {
        this.illimite = illimite;
    }

    
    @Column(name="etat")
    public Boolean getEtat() {
        return this.etat;
    }
    
    public void setEtat(Boolean etat) {
        this.etat = etat;
    }




}


