package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Groupe generated by hbm2java
 */
@Entity
@Table(name="groupe"
    ,schema="public"
)
public class Groupe  implements java.io.Serializable {


     private long codegroupe;
     private String nom;
     private Date datecreation;
     private Set messages = new HashSet(0);
     private Set clients = new HashSet(0);

    public Groupe() {
    }

	
    public Groupe(long codegroupe) {
        this.codegroupe = codegroupe;
    }
    public Groupe(long codegroupe, String nom, Date datecreation, Set messages, Set clients) {
       this.codegroupe = codegroupe;
       this.nom = nom;
       this.datecreation = datecreation;
       this.messages = messages;
       this.clients = clients;
    }
   
     @Id 

    
    @Column(name="codegroupe", nullable=false)
    public long getCodegroupe() {
        return this.codegroupe;
    }
    
    public void setCodegroupe(long codegroupe) {
        this.codegroupe = codegroupe;
    }

    
    @Column(name="nom", length=50)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datecreation", length=13)
    public Date getDatecreation() {
        return this.datecreation;
    }
    
    public void setDatecreation(Date datecreation) {
        this.datecreation = datecreation;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="groupe")
    public Set getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="groupes")
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }




}


