package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Jour generated by hbm2java
 */
@Entity
@Table(name="jour"
    ,schema="public"
)
public class Jour  implements java.io.Serializable {


     private int codejour;
     private String libelle;
     private Set calendrierservices = new HashSet(0);

    public Jour() {
    }

	
    public Jour(int codejour) {
        this.codejour = codejour;
    }
    public Jour(int codejour, String libelle, Set calendrierservices) {
       this.codejour = codejour;
       this.libelle = libelle;
       this.calendrierservices = calendrierservices;
    }
   
     @Id 

    
    @Column(name="codejour", nullable=false)
    public int getCodejour() {
        return this.codejour;
    }
    
    public void setCodejour(int codejour) {
        this.codejour = codejour;
    }

    
    @Column(name="libelle", length=50)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jour")
    public Set getCalendrierservices() {
        return this.calendrierservices;
    }
    
    public void setCalendrierservices(Set calendrierservices) {
        this.calendrierservices = calendrierservices;
    }




}


