package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LignedevisId generated by hbm2java
 */
@Embeddable
public class LignedevisId  implements java.io.Serializable {


     private String codedevis;
     private String codefamille;

    public LignedevisId() {
    }

    public LignedevisId(String codedevis, String codefamille) {
       this.codedevis = codedevis;
       this.codefamille = codefamille;
    }
   


    @Column(name="codedevis", nullable=false, length=50)
    public String getCodedevis() {
        return this.codedevis;
    }
    
    public void setCodedevis(String codedevis) {
        this.codedevis = codedevis;
    }


    @Column(name="codefamille", nullable=false, length=254)
    public String getCodefamille() {
        return this.codefamille;
    }
    
    public void setCodefamille(String codefamille) {
        this.codefamille = codefamille;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LignedevisId) ) return false;
		 LignedevisId castOther = ( LignedevisId ) other; 
         
		 return ( (this.getCodedevis()==castOther.getCodedevis()) || ( this.getCodedevis()!=null && castOther.getCodedevis()!=null && this.getCodedevis().equals(castOther.getCodedevis()) ) )
 && ( (this.getCodefamille()==castOther.getCodefamille()) || ( this.getCodefamille()!=null && castOther.getCodefamille()!=null && this.getCodefamille().equals(castOther.getCodefamille()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodedevis() == null ? 0 : this.getCodedevis().hashCode() );
         result = 37 * result + ( getCodefamille() == null ? 0 : this.getCodefamille().hashCode() );
         return result;
   }   


}


