package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Lignecommande generated by hbm2java
 */
@Entity
@Table(name="lignecommande"
    ,schema="public"
)
public class Lignecommande  implements java.io.Serializable {


     private LignecommandeId id;
     private Commande commande;
     private Famille famille;
     private Integer conditionnement;
     private Integer quantite;
     private BigDecimal prixunitaire;
     private BigDecimal prixtotal;
     private Boolean tva;

    public Lignecommande() {
    }

	
    public Lignecommande(LignecommandeId id, Commande commande, Famille famille) {
        this.id = id;
        this.commande = commande;
        this.famille = famille;
    }
    public Lignecommande(LignecommandeId id, Commande commande, Famille famille, Integer conditionnement, Integer quantite, BigDecimal prixunitaire, BigDecimal prixtotal, Boolean tva) {
       this.id = id;
       this.commande = commande;
       this.famille = famille;
       this.conditionnement = conditionnement;
       this.quantite = quantite;
       this.prixunitaire = prixunitaire;
       this.prixtotal = prixtotal;
       this.tva = tva;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codecommande", column=@Column(name="codecommande", nullable=false, length=50) ), 
        @AttributeOverride(name="codefamille", column=@Column(name="codefamille", nullable=false, length=254) ) } )
    public LignecommandeId getId() {
        return this.id;
    }
    
    public void setId(LignecommandeId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codecommande", nullable=false, insertable=false, updatable=false)
    public Commande getCommande() {
        return this.commande;
    }
    
    public void setCommande(Commande commande) {
        this.commande = commande;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codefamille", nullable=false, insertable=false, updatable=false)
    public Famille getFamille() {
        return this.famille;
    }
    
    public void setFamille(Famille famille) {
        this.famille = famille;
    }

    
    @Column(name="conditionnement")
    public Integer getConditionnement() {
        return this.conditionnement;
    }
    
    public void setConditionnement(Integer conditionnement) {
        this.conditionnement = conditionnement;
    }

    
    @Column(name="quantite")
    public Integer getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(Integer quantite) {
        this.quantite = quantite;
    }

    
    @Column(name="prixunitaire", precision=12)
    public BigDecimal getPrixunitaire() {
        return this.prixunitaire;
    }
    
    public void setPrixunitaire(BigDecimal prixunitaire) {
        this.prixunitaire = prixunitaire;
    }

    
    @Column(name="prixtotal", precision=12)
    public BigDecimal getPrixtotal() {
        return this.prixtotal;
    }
    
    public void setPrixtotal(BigDecimal prixtotal) {
        this.prixtotal = prixtotal;
    }

    
    @Column(name="tva")
    public Boolean getTva() {
        return this.tva;
    }
    
    public void setTva(Boolean tva) {
        this.tva = tva;
    }




}


