package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Livreur generated by hbm2java
 */
@Entity
@Table(name="livreur"
    ,schema="public"
)
public class Livreur  implements java.io.Serializable {


     private String codepersonne;
     private Employe employe;
     private Integer nombrelivraison;
     private Set livraisons = new HashSet(0);

    public Livreur() {
    }

	
    public Livreur(Employe employe) {
        this.employe = employe;
    }
    public Livreur(Employe employe, Integer nombrelivraison, Set livraisons) {
       this.employe = employe;
       this.nombrelivraison = nombrelivraison;
       this.livraisons = livraisons;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="employe"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="codepersonne", nullable=false, length=40)
    public String getCodepersonne() {
        return this.codepersonne;
    }
    
    public void setCodepersonne(String codepersonne) {
        this.codepersonne = codepersonne;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }

    
    @Column(name="nombrelivraison")
    public Integer getNombrelivraison() {
        return this.nombrelivraison;
    }
    
    public void setNombrelivraison(Integer nombrelivraison) {
        this.nombrelivraison = nombrelivraison;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="livreur")
    public Set getLivraisons() {
        return this.livraisons;
    }
    
    public void setLivraisons(Set livraisons) {
        this.livraisons = livraisons;
    }




}


