package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Livraison generated by hbm2java
 */
@Entity
@Table(name="livraison"
    ,schema="public"
)
public class Livraison  implements java.io.Serializable {


     private String codelivraison;
     private Livreur livreur;
     private Panierclient panierclient;
     private Date datelivraison;

    public Livraison() {
    }

	
    public Livraison(String codelivraison, Livreur livreur, Panierclient panierclient) {
        this.codelivraison = codelivraison;
        this.livreur = livreur;
        this.panierclient = panierclient;
    }
    public Livraison(String codelivraison, Livreur livreur, Panierclient panierclient, Date datelivraison) {
       this.codelivraison = codelivraison;
       this.livreur = livreur;
       this.panierclient = panierclient;
       this.datelivraison = datelivraison;
    }
   
     @Id 

    
    @Column(name="codelivraison", nullable=false, length=50)
    public String getCodelivraison() {
        return this.codelivraison;
    }
    
    public void setCodelivraison(String codelivraison) {
        this.codelivraison = codelivraison;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codelivreur", nullable=false)
    public Livreur getLivreur() {
        return this.livreur;
    }
    
    public void setLivreur(Livreur livreur) {
        this.livreur = livreur;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codepanier", nullable=false)
    public Panierclient getPanierclient() {
        return this.panierclient;
    }
    
    public void setPanierclient(Panierclient panierclient) {
        this.panierclient = panierclient;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datelivraison", length=13)
    public Date getDatelivraison() {
        return this.datelivraison;
    }
    
    public void setDatelivraison(Date datelivraison) {
        this.datelivraison = datelivraison;
    }




}


