package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Panier generated by hbm2java
 */
@Entity
@Table(name="panier"
    ,schema="public"
)
public class Panier  implements java.io.Serializable {


     private String codepanier;
     private Date datepanier;
     private BigDecimal prix;
     private Paniercaissier paniercaissier;
     private Set produits = new HashSet(0);
     private Panierclient panierclient;

    public Panier() {
    }

	
    public Panier(String codepanier) {
        this.codepanier = codepanier;
    }
    public Panier(String codepanier, Date datepanier, BigDecimal prix, Paniercaissier paniercaissier, Set produits, Panierclient panierclient) {
       this.codepanier = codepanier;
       this.datepanier = datepanier;
       this.prix = prix;
       this.paniercaissier = paniercaissier;
       this.produits = produits;
       this.panierclient = panierclient;
    }
   
     @Id 

    
    @Column(name="codepanier", nullable=false, length=50)
    public String getCodepanier() {
        return this.codepanier;
    }
    
    public void setCodepanier(String codepanier) {
        this.codepanier = codepanier;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datepanier", length=13)
    public Date getDatepanier() {
        return this.datepanier;
    }
    
    public void setDatepanier(Date datepanier) {
        this.datepanier = datepanier;
    }

    
    @Column(name="prix", precision=12)
    public BigDecimal getPrix() {
        return this.prix;
    }
    
    public void setPrix(BigDecimal prix) {
        this.prix = prix;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="panier")
    public Paniercaissier getPaniercaissier() {
        return this.paniercaissier;
    }
    
    public void setPaniercaissier(Paniercaissier paniercaissier) {
        this.paniercaissier = paniercaissier;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="panier")
    public Set getProduits() {
        return this.produits;
    }
    
    public void setProduits(Set produits) {
        this.produits = produits;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="panier")
    public Panierclient getPanierclient() {
        return this.panierclient;
    }
    
    public void setPanierclient(Panierclient panierclient) {
        this.panierclient = panierclient;
    }




}


