package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Panierclient generated by hbm2java
 */
@Entity
@Table(name="panierclient"
    ,schema="public"
)
public class Panierclient  implements java.io.Serializable {


     private String codepanier;
     private Client client;
     private Panier panier;
     private String adresselivraison;
     private String typepaiement;
     private String bonlivraison;
     private Set livraisons = new HashSet(0);

    public Panierclient() {
    }

	
    public Panierclient(Client client, Panier panier) {
        this.client = client;
        this.panier = panier;
    }
    public Panierclient(Client client, Panier panier, String adresselivraison, String typepaiement, String bonlivraison, Set livraisons) {
       this.client = client;
       this.panier = panier;
       this.adresselivraison = adresselivraison;
       this.typepaiement = typepaiement;
       this.bonlivraison = bonlivraison;
       this.livraisons = livraisons;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="panier"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="codepanier", nullable=false, length=50)
    public String getCodepanier() {
        return this.codepanier;
    }
    
    public void setCodepanier(String codepanier) {
        this.codepanier = codepanier;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codeclient", nullable=false)
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Panier getPanier() {
        return this.panier;
    }
    
    public void setPanier(Panier panier) {
        this.panier = panier;
    }

    
    @Column(name="adresselivraison", length=50)
    public String getAdresselivraison() {
        return this.adresselivraison;
    }
    
    public void setAdresselivraison(String adresselivraison) {
        this.adresselivraison = adresselivraison;
    }

    
    @Column(name="typepaiement", length=50)
    public String getTypepaiement() {
        return this.typepaiement;
    }
    
    public void setTypepaiement(String typepaiement) {
        this.typepaiement = typepaiement;
    }

    
    @Column(name="bonlivraison", length=50)
    public String getBonlivraison() {
        return this.bonlivraison;
    }
    
    public void setBonlivraison(String bonlivraison) {
        this.bonlivraison = bonlivraison;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="panierclient")
    public Set getLivraisons() {
        return this.livraisons;
    }
    
    public void setLivraisons(Set livraisons) {
        this.livraisons = livraisons;
    }




}


