package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Personne generated by hbm2java
 */
@Entity
@Table(name="personne"
    ,schema="public"
)
public class Personne  implements java.io.Serializable {


     private String codepersonne;
     private String prenom;
     private String nom;
     private String datenaiss;
     private String lieunaiss;
     private String adresse;
     private String telephone;
     private String email;
     private String nationalite;
     private String sexe;
     private String login;
     private String motpasse;
     private String droit;
     private Boolean session;
     private Integer nombreconnexion;
     private Integer codeaccess;
     private Integer bloque;
     private String photo;
     private String profil;
     private Set messagesForCodedestinataire = new HashSet(0);
     private Employe employe;
     private Administrateur administrateur;
     private Client client;
     private Set messagesForCodeenvoyeur = new HashSet(0);
     private Fournisseur fournisseur;

    public Personne() {
    }

	
    public Personne(String codepersonne, String prenom, String nom) {
        this.codepersonne = codepersonne;
        this.prenom = prenom;
        this.nom = nom;
    }
    public Personne(String codepersonne, String prenom, String nom, String datenaiss, String lieunaiss, String adresse, String telephone, String email, String nationalite, String sexe, String login, String motpasse, String droit, Boolean session, Integer nombreconnexion, Integer codeaccess, Integer bloque, String photo, String profil, Set messagesForCodedestinataire, Employe employe, Administrateur administrateur, Client client, Set messagesForCodeenvoyeur, Fournisseur fournisseur) {
       this.codepersonne = codepersonne;
       this.prenom = prenom;
       this.nom = nom;
       this.datenaiss = datenaiss;
       this.lieunaiss = lieunaiss;
       this.adresse = adresse;
       this.telephone = telephone;
       this.email = email;
       this.nationalite = nationalite;
       this.sexe = sexe;
       this.login = login;
       this.motpasse = motpasse;
       this.droit = droit;
       this.session = session;
       this.nombreconnexion = nombreconnexion;
       this.codeaccess = codeaccess;
       this.bloque = bloque;
       this.photo = photo;
       this.profil = profil;
       this.messagesForCodedestinataire = messagesForCodedestinataire;
       this.employe = employe;
       this.administrateur = administrateur;
       this.client = client;
       this.messagesForCodeenvoyeur = messagesForCodeenvoyeur;
       this.fournisseur = fournisseur;
    }
   
     @Id 

    
    @Column(name="codepersonne", nullable=false, length=40)
    public String getCodepersonne() {
        return this.codepersonne;
    }
    
    public void setCodepersonne(String codepersonne) {
        this.codepersonne = codepersonne;
    }

    
    @Column(name="prenom", nullable=false, length=50)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="nom", nullable=false, length=50)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="datenaiss", length=20)
    public String getDatenaiss() {
        return this.datenaiss;
    }
    
    public void setDatenaiss(String datenaiss) {
        this.datenaiss = datenaiss;
    }

    
    @Column(name="lieunaiss", length=50)
    public String getLieunaiss() {
        return this.lieunaiss;
    }
    
    public void setLieunaiss(String lieunaiss) {
        this.lieunaiss = lieunaiss;
    }

    
    @Column(name="adresse", length=50)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="telephone", length=40)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    
    @Column(name="email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="nationalite", length=50)
    public String getNationalite() {
        return this.nationalite;
    }
    
    public void setNationalite(String nationalite) {
        this.nationalite = nationalite;
    }

    
    @Column(name="sexe", length=1)
    public String getSexe() {
        return this.sexe;
    }
    
    public void setSexe(String sexe) {
        this.sexe = sexe;
    }

    
    @Column(name="login", length=50)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="motpasse", length=50)
    public String getMotpasse() {
        return this.motpasse;
    }
    
    public void setMotpasse(String motpasse) {
        this.motpasse = motpasse;
    }

    
    @Column(name="droit", length=50)
    public String getDroit() {
        return this.droit;
    }
    
    public void setDroit(String droit) {
        this.droit = droit;
    }

    
    @Column(name="session")
    public Boolean getSession() {
        return this.session;
    }
    
    public void setSession(Boolean session) {
        this.session = session;
    }

    
    @Column(name="nombreconnexion")
    public Integer getNombreconnexion() {
        return this.nombreconnexion;
    }
    
    public void setNombreconnexion(Integer nombreconnexion) {
        this.nombreconnexion = nombreconnexion;
    }

    
    @Column(name="codeaccess")
    public Integer getCodeaccess() {
        return this.codeaccess;
    }
    
    public void setCodeaccess(Integer codeaccess) {
        this.codeaccess = codeaccess;
    }

    
    @Column(name="bloque")
    public Integer getBloque() {
        return this.bloque;
    }
    
    public void setBloque(Integer bloque) {
        this.bloque = bloque;
    }

    
    @Column(name="photo", length=254)
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    
    @Column(name="profil", length=20)
    public String getProfil() {
        return this.profil;
    }
    
    public void setProfil(String profil) {
        this.profil = profil;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personneByCodedestinataire")
    public Set getMessagesForCodedestinataire() {
        return this.messagesForCodedestinataire;
    }
    
    public void setMessagesForCodedestinataire(Set messagesForCodedestinataire) {
        this.messagesForCodedestinataire = messagesForCodedestinataire;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="personne")
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="personne")
    public Administrateur getAdministrateur() {
        return this.administrateur;
    }
    
    public void setAdministrateur(Administrateur administrateur) {
        this.administrateur = administrateur;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="personne")
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personneByCodeenvoyeur")
    public Set getMessagesForCodeenvoyeur() {
        return this.messagesForCodeenvoyeur;
    }
    
    public void setMessagesForCodeenvoyeur(Set messagesForCodeenvoyeur) {
        this.messagesForCodeenvoyeur = messagesForCodeenvoyeur;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="personne")
    public Fournisseur getFournisseur() {
        return this.fournisseur;
    }
    
    public void setFournisseur(Fournisseur fournisseur) {
        this.fournisseur = fournisseur;
    }




}


