package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Privilege generated by hbm2java
 */
@Entity
@Table(name="privilege"
    ,schema="public"
)
public class Privilege  implements java.io.Serializable {


     private int codeprivilege;
     private String intitule;
     private String description;
     private Set gerantprivileges = new HashSet(0);

    public Privilege() {
    }

	
    public Privilege(int codeprivilege) {
        this.codeprivilege = codeprivilege;
    }
    public Privilege(int codeprivilege, String intitule, String description, Set gerantprivileges) {
       this.codeprivilege = codeprivilege;
       this.intitule = intitule;
       this.description = description;
       this.gerantprivileges = gerantprivileges;
    }
   
     @Id 

    
    @Column(name="codeprivilege", nullable=false)
    public int getCodeprivilege() {
        return this.codeprivilege;
    }
    
    public void setCodeprivilege(int codeprivilege) {
        this.codeprivilege = codeprivilege;
    }

    
    @Column(name="intitule", length=50)
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="privilege")
    public Set getGerantprivileges() {
        return this.gerantprivileges;
    }
    
    public void setGerantprivileges(Set gerantprivileges) {
        this.gerantprivileges = gerantprivileges;
    }




}


