package com.treluxcom.metier;
// Generated 9 juin 2018 12:35:35 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ressourcemedia generated by hbm2java
 */
@Entity
@Table(name="ressourcemedia"
    ,schema="public"
)
public class Ressourcemedia  implements java.io.Serializable {


     private int coderessource;
     private Famille famille;
     private String libelle;
     private String localisation;

    public Ressourcemedia() {
    }

	
    public Ressourcemedia(int coderessource, Famille famille) {
        this.coderessource = coderessource;
        this.famille = famille;
    }
    public Ressourcemedia(int coderessource, Famille famille, String libelle, String localisation) {
       this.coderessource = coderessource;
       this.famille = famille;
       this.libelle = libelle;
       this.localisation = localisation;
    }
   
     @Id 

    
    @Column(name="coderessource", nullable=false)
    public int getCoderessource() {
        return this.coderessource;
    }
    
    public void setCoderessource(int coderessource) {
        this.coderessource = coderessource;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codefamille", nullable=false)
    public Famille getFamille() {
        return this.famille;
    }
    
    public void setFamille(Famille famille) {
        this.famille = famille;
    }

    
    @Column(name="libelle", length=50)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="localisation", length=50)
    public String getLocalisation() {
        return this.localisation;
    }
    
    public void setLocalisation(String localisation) {
        this.localisation = localisation;
    }




}


